# Demo generation configuration
num_episodes: 100
num_workers: 4
episode_length: 1000
image_size: [128, 128]

# Scripted policy parameters
scripted_policy:
  noise_level: 0.1
  suction_threshold: 0.5
  movement_scale: 0.05
  suction_probability: 0.3

# Demo quality filtering
quality_filtering:
  enabled: true
  min_liquid_reduction: 0.3
  min_contaminant_reduction: 0.2
  max_collision_rate: 0.1
  max_safety_violations: 0.05

# Weight calculation
weighting:
  enabled: true
  gmm_components: 2
  features:
    - liquid_reduction
    - contaminant_reduction
    - smoothness
    - safety_compliance
  weights:
    liquid_reduction: 0.4
    contaminant_reduction: 0.3
    smoothness: 0.2
    safety_compliance: 0.1