# Paths configuration
data_dir: "data"
sim_dir: "sim"
unity_build: "sim/CRESSim/Builds/SuctionEnv.x86_64"
kvasir_seg_dir: "data/kvasir_seg"
demos_dir: "data/demos"
checkpoints_dir: "data/checkpoints"
logs_dir: "data/logs"
videos_dir: "data/videos"
benchmarks_dir: "data/benchmarks"
models_dir: "data/models"
eval_dir: "data/eval"