# File paths configuration
data_dir: ./data
sim_dir: ./sim/CRESSim
unity_build: ./sim/CRESSim/Build/SuctionEnv.exe

# Dataset paths
kvasir_seg_dir: ./data/kvasir_seg
endoscapes_dir: ./data/endoscapes
cholec80_dir: ./data/cholec80

# Output paths
demos_dir: ./data/demos
logs_dir: ./data/logs
videos_dir: ./data/videos
checkpoints_dir: ./data/checkpoints
benchmarks_dir: ./data/benchmarks

# Logging
tensorboard_dir: ./data/logs/tensorboard
csv_logs_dir: ./data/logs/csv
